### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by chefente** [cflurin/homebridge-punt#1]
[ Error writing /home/pi/.homebridge/plugins/homebridge-punt/config-punt.json: ]

**Comment by cflurin** [comment]
When did you get this error?
Could you please provide more details.

**Comment by chefente** [comment]
I tried to Write the config.json on home/Pi/.homebridge/

Command + o and enter an it appeared 

Mit freundlichen Grüßen 

Dennis Zagorski

**Comment by chefente** [comment]
Honestly i guess i need a Tutorial...i just want to Control my Philips hue over Siri without buying The New bridge 

Mit freundlichen Grüßen 

Dennis Zagorski

**Comment by cflurin** [comment]
Do you use Fhem? Otherwise there is a Homebridge Plugin for Philips hue: homebridge-philipshue.

**Comment by chefente** [comment]
Yeah i used fhem but its not neccessary, can you sum up what i have to Do?

Mit freundlichen Grüßen 

Dennis Zagorski

**Comment by cflurin** [comment]
If you only want to use a Philips hue, take a look [here](https://www.npmjs.com/package/homebridge-philipshue).

**Comment by chefente** [comment]
so which config is the right one? do you have the command for this one? so i can insert the changes

**Comment by chefente** [comment]
okay i got this one, but my iPhone still don’t find the homebridge

**Comment by cflurin** [comment]
Hmm, which Plugin are you using now homebridge-punt or homebridge-philipshue?

**Comment by chefente** [comment]
Loaded plugin: homebridge-philipshue

## Registering platform 'homebridge-philipshue.PhilipsHue'

Loaded plugin: homebridge-punt

## Registering platform 'homebridge-punt.punt'

## Loaded config.json with 0 accessories and 1 platforms.

Loading 1 platforms...
[punt] Initializing punt platform...
Couldn't find a config-punt.json file at /home/pi/.homebridge/plugins/homebridge-punt.

**Comment by cflurin** [comment]
As you obviously only need homebridge-philipshue, uninstall homebridge-punt

``` sh
sudo npm uninstall -g homebridge-punt
```

**Comment by chefente** [comment]
Done, still not working! Seems like its all messed up! Guess homebridge is still reading the Second json i needed for punt at some point 

Mit freundlichen Grüßen 

Dennis Zagorski

**Comment by cflurin** [comment]
Please read the documentation on Homebridge [here](https://github.com/nfarina/homebridge)

**Comment by chefente** [comment]
its not working…but maybe you can solve this one [punt] Initializing punt platform...
Couldn't find a config-punt.json file at /home/pi/.homebridge/plugins/homebridge-punt.

**Comment by cflurin** [comment]
uninstall `homebridge-punt` if you don't need it:

``` sh
sudo npm uninstall -g homebridge-punt
```

or read the documentation and define `config-punt.json` in the folder:

``` sh
/home/pi/.homebridge/plugins/homebridge-punt
```

**Comment by chefente** [comment]
I don't get to define it...whats The Command?

Mit freundlichen Grüßen 

Dennis Zagorski

**Comment by cflurin** [comment]
If you are new to Raspberry Pi / Raspbian, please take a look [here](https://www.raspberrypi.org/documentation/linux/).

**Comment by chefente** [comment]
Sorry but it´s one last mail.

pi@raspberrypi ~ $ homebridge
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
Loaded plugin: homebridge-philipshue

## Registering platform 'homebridge-philipshue.PhilipsHue'

Loaded plugin: homebridge-punt

## Registering platform 'homebridge-punt.punt'

## Loaded config.json with 0 accessories and 1 platforms.

Loading 1 platforms...
[punt] Initializing punt platform...
[punt] homebridge-punt v0.1.5
[punt] Reading 1 Accessories
[punt] Initializing platform accessory 'Boden'...
Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

```
┌────────────┐     
│ 031-45-154 │     
└────────────┘     
```

Homebridge is running on port 51826.
[punt] Monitor is running on port 8081

TypeError: Cannot call method 'get' of undefined
    at Gateway.<anonymous> (/usr/local/lib/node_modules/homebridge-punt/gateway.js:218:18)
    at Timer.listOnTimeout [as ontimeout](timers.js:110:15)

It runs like this, but I can’t find the homebridge in my elgato eve app. Any idea?

**Comment by chefente** [comment]
Hey, can you see anything i did wrong? its running like this but my iPhone don’t find the bridge, the monitor is running as well and i deleted the persist and changed the name. 

pi@raspberrypi ~ $ homebridge
**\* WARNING **\* The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node
**\* WARNING **\* The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
**\* WARNING **\* Please fix your application to use the native API of Avahi!
**\* WARNING **\* For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister
Loaded plugin: homebridge-philipshue

## Registering platform 'homebridge-philipshue.PhilipsHue'

Loaded plugin: homebridge-punt

## Registering platform 'homebridge-punt.punt'

## Loaded config.json with 0 accessories and 1 platforms.

Loading 1 platforms...
[punt] Initializing punt platform...
[punt] homebridge-punt v0.1.6
[punt] Reading 7 Accessories
[punt] Initializing platform accessory 'alarm_control'...
[punt] Initializing platform accessory 'temp_control'...
[punt] Initializing platform accessory 'flex_lamp'...
[punt] Initializing platform accessory 'garden_door'...
[punt] Initializing platform accessory 'local_weather'...
[punt] Initializing platform accessory 'led_bulb'...
[punt] Initializing platform accessory 'bathroom_blind'...
Loading 0 accessories...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

```
┌────────────┐     
│ 031-45-154 │     
└────────────┘     
```

Homebridge is running on port 51826.
[punt] Monitor is running on port 8081
[punt] homebridge-punt a new version 0.1.6
 is avaiable
