### ISSUE TITLE
error while install npm

### ISSUE THREAD

**Issue by dapelza** [cflurin/homebridge-punt#4]
Hi! 
i wanted to do: 
npm install

this is what it said: 
![bildschirmfoto 2015-12-12 um 18 53 13](https://cloud.githubusercontent.com/assets/16230077/11763194/a3f6061c-a101-11e5-928f-ae9f86d6ea31.png)

**Comment by dapelza** [comment]
after 
npm cache clean the same problem, 
npm install: 

![bildschirmfoto 2015-12-12 um 18 55 22](https://cloud.githubusercontent.com/assets/16230077/11763207/0dad4a98-a102-11e5-87e3-66a2baa57177.png)

**Comment by dapelza** [comment]
do i need a c++11 compiler? 
Where can i get it?

**Comment by captaineramirez** [comment]
I've got the same errors after doing node update see bellow log file

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'install' ]
2 info using npm@5.6.0
3 info using node@v9.8.0
4 verbose npm-session 2f874197010bbba3
5 verbose stack Error: Cannot find module 'internal/util/types'
5 verbose stack     at Function.Module._resolveFilename (module.js:543:15)
5 verbose stack     at Function.Module._load (module.js:470:25)
5 verbose stack     at Module.require (module.js:593:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at evalmachine.<anonymous>:31:26
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_m$
5 verbose stack     at Module._compile (module.js:649:30)
5 verbose stack     at Object.Module._extensions..js (module.js:660:10)
5 verbose stack     at Module.load (module.js:561:32)
5 verbose stack     at tryModuleLoad (module.js:501:12)
5 verbose stack     at Function.Module._load (module.js:493:3)
5 verbose stack     at Module.require (module.js:593:17)
5 verbose stack     at require (internal/module.js:11:18)
5 verbose stack     at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_m$
5 verbose stack     at Module._compile (module.js:649:30)
5 verbose stack     at Object.Module._extensions..js (module.js:660:10)
6 verbose cwd /home/pi
7 verbose Linux 4.9.35-v7+
8 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
9 verbose node v9.8.0
10 verbose npm  v5.6.0
11 error code MODULE_NOT_FOUND
12 error Cannot find module 'internal/util/types'
13 verbose exit [ 1, true ]
